# Generated by Django 2.2.15 on 2021-04-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Selected', max_length=15)),
            ],
            options={
                'ordering': ['-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='auditionRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
                ('round_status', models.BooleanField(default=False)),
                ('candidate', models.ManyToManyField(blank=True, null=True, related_name='candidates', to='audition.Candidates')),
            ],
        ),
        migrations.CreateModel(
            name='auditionQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
                ('serialno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=5000)),
                ('qtype', models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SMALL', 'SMALL'), ('MCQ', 'MCQ')], default='LONG', max_length=15, null=True)),
                ('op1', models.CharField(blank=True, max_length=5000, null=True)),
                ('op2', models.CharField(blank=True, max_length=5000, null=True)),
                ('op3', models.CharField(blank=True, max_length=5000, null=True)),
                ('op4', models.CharField(blank=True, max_length=5000, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='audition.auditionRounds')),
            ],
            options={
                'ordering': ['roundno', 'serialno'],
                'unique_together': {('roundno', 'serialno')},
            },
        ),
        migrations.CreateModel(
            name='auditionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
                ('ans', models.CharField(max_length=800)),
                ('anstime', models.DateTimeField(auto_now=True)),
                ('ansby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='audition.Candidates')),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='audition.auditionQuestions')),
            ],
        ),
    ]
