# Generated by Django 3.2.6 on 2021-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debator',
            name='ss',
            field=models.ImageField(blank=True, null=True, upload_to='payment_ss/'),
        ),
    ]
