# Generated by Django 3.2.6 on 2021-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oud', '0002_debator_ss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(max_length=100)),
                ('college_year', models.IntegerField(default='1')),
                ('discord_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prior', models.CharField(blank=True, max_length=200, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('ss', models.ImageField(blank=True, null=True, upload_to='payment_ss/')),
                ('is_adj', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Adj',
        ),
        migrations.DeleteModel(
            name='Debator',
        ),
    ]
