# Generated by Django 2.2.15 on 2021-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oud', '0003_auto_20210831_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
