# Generated by Django 3.0.7 on 2020-06-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='post',
        ),
    ]
