# Generated by Django 3.0.7 on 2020-07-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0003_auto_20200701_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='twitter_url',
            new_name='instagram_url',
        ),
    ]
