# Generated by Django 2.2.15 on 2020-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0004_auto_20200726_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(verbose_name='Date of event : '),
        ),
    ]
