# Generated by Django 2.2.15 on 2020-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0005_auto_20200813_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='year',
            field=models.CharField(choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='Second', max_length=10),
        ),
    ]
