# Generated by Django 2.2.15 on 2020-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0006_auto_20200813_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dp',
            field=models.ImageField(null=True, upload_to='memberDPs/'),
        ),
    ]
