# Generated by Django 2.2.15 on 2020-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0007_auto_20200813_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='memberDPs/'),
        ),
    ]
