# Generated by Django 2.2.15 on 2021-01-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0009_auto_20201210_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='audtionRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'ordering': ['-status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='auditionQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
                ('serialno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=5000)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='sitewebapp.audtionRounds')),
            ],
            options={
                'ordering': ['roundno', 'serialno'],
                'unique_together': {('roundno', 'serialno')},
            },
        ),
        migrations.CreateModel(
            name='auditionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=5000)),
                ('anstime', models.DateTimeField(auto_now=True)),
                ('ansby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='sitewebapp.Candidates')),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='sitewebapp.auditionQuestions')),
            ],
        ),
    ]
