# Generated by Django 2.2.15 on 2021-01-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0010_auditionanswers_auditionquestions_audtionrounds_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditionRounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundno', models.IntegerField(default=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inductees', to='sitewebapp.Candidates')),
            ],
        ),
        migrations.AlterField(
            model_name='auditionquestions',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='sitewebapp.auditionRounds'),
        ),
        migrations.DeleteModel(
            name='audtionRounds',
        ),
    ]
