# Generated by Django 2.2.15 on 2021-01-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0013_auto_20210130_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionrounds',
            name='candidate',
        ),
        migrations.AddField(
            model_name='auditionrounds',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='sitewebapp.Candidates'),
        ),
    ]
