# Generated by Django 2.2.15 on 2021-01-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0015_auto_20210130_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionrounds',
            name='round_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditionrounds',
            name='candidate',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='sitewebapp.Candidates'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
