# Generated by Django 2.2.15 on 2021-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0016_auto_20210130_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionanswers',
            name='roundno',
            field=models.IntegerField(default=1),
        ),
    ]
