# Generated by Django 2.2.15 on 2021-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0017_auditionanswers_roundno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
    ]
