# Generated by Django 2.2.15 on 2021-01-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0018_auto_20210130_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Selected', max_length=15),
        ),
    ]
