# Generated by Django 2.2.15 on 2021-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0020_auto_20210131_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionquestions',
            name='op1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='auditionquestions',
            name='op2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='auditionquestions',
            name='op3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='auditionquestions',
            name='op4',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='auditionquestions',
            name='qtype',
            field=models.CharField(blank=True, choices=[('LONG', 'LONG'), ('SMALL', 'SMALL'), ('MCQ', 'MCQ')], default='LONG', max_length=15, null=True),
        ),
    ]
