# Generated by Django 2.2.15 on 2021-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0022_auto_20210208_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='text2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='text3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
