# Generated by Django 2.2.15 on 2021-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0023_auto_20210208_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='2017', max_length=10)),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='memberDPs/')),
                ('facebook_url', models.URLField(blank=True, max_length=300, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=300, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
