# Generated by Django 2.2.15 on 2021-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0024_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='dp',
        ),
        migrations.AddField(
            model_name='alumni',
            name='propic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
