# Generated by Django 2.2.15 on 2021-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0025_auto_20210607_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.CharField(default='2017', max_length=10),
        ),
    ]
