# Generated by Django 2.2.15 on 2021-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0026_auto_20210607_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='token', max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
