# Generated by Django 2.2.15 on 2022-07-14 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0028_auto_20220609_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='propic',
        ),
        migrations.AddField(
            model_name='alumni',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='memberDPs/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 18, 39, 442297), verbose_name='End date of the event: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 18, 39, 442276), verbose_name='Start Date of the event: '),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
