# Generated by Django 2.2.15 on 2022-07-14 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitewebapp', '0029_auto_20220714_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='alumniDPs/'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 20, 58, 458882), verbose_name='End date of the event: '),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 7, 20, 58, 458862), verbose_name='Start Date of the event: '),
        ),
    ]
